# infra/serverless.yml
service: pro-irp-mvp

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    USERS_TABLE: ${self:service}-users
    CLIENTS_TABLE: ${self:service}-clients
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  auth:
    handler: backend/handlers/auth.handler
    events:
      - http:
          path: signup
          method: post
      - http:
          path: login
          method: post

  clients:
    handler: backend/handlers/clients.handler
    events:
      - http:
          path: clients
          method: get
      - http:
          path: clients
          method: post
      - http:
          path: clients
          method: put
      - http:
          path: clients
          method: delete

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CLIENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: owner
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: owner
            KeyType: HASH
          - AttributeName: clientId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
