jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v3
        with:
          ref: staging
          token: ${{ secrets.MACHINE_USER_PAT }}

      - name: Fetch ai-code branch
        run: |
          git fetch origin ai-code

      - name: Merge ai-code into staging
        run: |
          git merge --no-ff origin/ai-code -m "chore: merge ai-code into staging"

      - name: Push to staging
        run: |
          git push https://${{ secrets.MACHINE_USER_PAT }}@github.com/your-username/pro-irp.git staging
